######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 18 14:50:06 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clockwindow.h 
SOURCES += clockwindow.cc main.cc
